[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install build-essential:$CROSS_DEB_ARCH clang-tools-18:$CROSS_DEB_ARCH libclang-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH libavutil-dev:$CROSS_DEB_ARCH libavcodec-dev:$CROSS_DEB_ARCH libavformat-dev:$CROSS_DEB_ARCH libavfilter-dev:$CROSS_DEB_ARCH libavdevice-dev:$CROSS_DEB_ARCH libtesseract-dev:$CROSS_DEB_ARCH"
]

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:noble"
